services:
  redis-test:
    build: .
    ports:
      - "${HOST_PORT:-5004}:3000"
    environment:
      PORT: 3000
      REDIS_MODE: cluster
      REDIS_CLUSTER_NODES: redis-node-1:7001,redis-node-2:7002,redis-node-3:7003,redis-node-4:7004,redis-node-5:7005,redis-node-6:7006
    networks:
      - default
      - redis_cluster
    restart: unless-stopped

networks:
  redis_cluster:
    external: true
    name: redis-enterprise-cluster_redis-cluster-net
